name: test nodejs
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
      - run: npm install
      - run: npm start
      - run: npm test
      - run: npm run cover
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: /home/runner/work/quick-example-of-testing-in-nodejs/quick-example-of-testing-in-nodejs/reports/