name: test nodejs
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
      - run: npm install
      - run: npm start
      - run: npm test